
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NCRSocialNetwork.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ClubSubscribe
{

    public int ClubSubscribeId { get; set; }

    public int ClubSubscribeClubId { get; set; }

    public int ClubSubscribeUserId { get; set; }



    public virtual User User { get; set; }

    public virtual Club Club { get; set; }

}

}
