
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NCRSocialNetwork.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public Event()
    {

        this.EventLikeDislikes = new HashSet<EventLikeDislike>();

        this.EventAttendings = new HashSet<EventAttending>();

    }


    public int EventId { get; set; }

    public string EventName { get; set; }

    public string EventDescription { get; set; }

    public int EventClubId { get; set; }

    public string EventVenue { get; set; }

    public System.DateTime EventDateTime { get; set; }

    public Nullable<int> EventEventRequestId { get; set; }

    public int EventCreatedBy { get; set; }

    public System.DateTime EventCreatedTime { get; set; }



    public virtual User User { get; set; }

    public virtual Club Club { get; set; }

    public virtual Key Key { get; set; }

    public virtual ICollection<EventLikeDislike> EventLikeDislikes { get; set; }

    public virtual ICollection<EventAttending> EventAttendings { get; set; }

    public virtual EventRequest EventRequest { get; set; }

}

}
