
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NCRSocialNetwork.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Feedback
{

    public int FeedbackId { get; set; }

    public int FeedbackUserId { get; set; }

    public string FeedbackDescription { get; set; }

    public string FeedbackCreatedDate { get; set; }



    public virtual User User { get; set; }

}

}
