
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NCRSocialNetwork.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Key
{

    public Key()
    {

        this.Comments = new HashSet<Comment>();

    }


    public int KeyId { get; set; }

    public string KeyType { get; set; }

    public System.DateTime KeyCreatedDate { get; set; }



    public virtual Club Clubs { get; set; }

    public virtual Event Events { get; set; }

    public virtual ICollection<Comment> Comments { get; set; }

}

}
