
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NCRSocialNetwork.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.UserDisplayPicture = "/NCRSocialNetwork/Content/Images/UserDisplayPicture.png";

        this.Events = new HashSet<Event>();

        this.Comments = new HashSet<Comment>();

        this.EventLikeDislikes = new HashSet<EventLikeDislike>();

        this.EventRequests = new HashSet<EventRequest>();

        this.ClubSubscribe = new HashSet<ClubSubscribe>();

        this.EventAttendings = new HashSet<EventAttending>();

        this.ClubModerators = new HashSet<ClubModerator>();

        this.Feedbacks = new HashSet<Feedback>();

    }


    public int UserId { get; set; }

    public string UserFirstName { get; set; }

    public string UserLastName { get; set; }

    public string UserQuicklookId { get; set; }

    public string UserRole { get; set; }

    public string UserEmail { get; set; }

    public string UserContactNo { get; set; }

    public string UserHobbies { get; set; }

    public string UserTechnologies { get; set; }

    public string UserDisplayPicture { get; set; }



    public virtual ICollection<Event> Events { get; set; }

    public virtual ICollection<Comment> Comments { get; set; }

    public virtual ICollection<EventLikeDislike> EventLikeDislikes { get; set; }

    public virtual ICollection<EventRequest> EventRequests { get; set; }

    public virtual ICollection<ClubSubscribe> ClubSubscribe { get; set; }

    public virtual ICollection<EventAttending> EventAttendings { get; set; }

    public virtual ICollection<ClubModerator> ClubModerators { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; }

}

}
